build separated commands into a single command line builder
morganstanley/Crossroads pull request #24
Opened 2022-03-23 08:26 UTC by pkErbynn

this combines separated modes (tool, luncher) commands into a single consolidated command line builder,
allowing automatic dynamic runtime mode determination and code command reusability

2022-03-23 08:43 UTC, pkErbynn commented
@bagdxk kindly review and give feedback if any, thanks

2022-03-23 09:42 UTC, bagdxk requested changes

2022-03-23 09:42 UTC, bagdxk commented on src/Crossroads/Properties/launchSettings.json
> +      "commandLineArgs": "inspect --package newnotepad.exe"
not add test in config.

2022-03-23 09:49 UTC, pkErbynn commented on src/Crossroads/Properties/launchSettings.json
> +      "commandLineArgs": "inspect --package newnotepad.exe"
alright sure, will remove it

2022-03-24 09:53 UTC, pkErbynn commented
closed as currently merged pr has all changes

2022-03-24 09:53 UTC, closed without merging